<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE document [
    <!ELEMENT document (employee)*>
    <!ELEMENT employee (name+, hiredate?, projects*)> 
    <!ELEMENT name (lastname, firstname)>
    <!ELEMENT lastname (#PCDATA)>
    <!ELEMENT firstname (#PCDATA)>
    <!ELEMENT hiredate (#PCDATA)>
    <!ELEMENT projects (project)*>
    <!ELEMENT project (product,id,price)>
    <!ELEMENT product (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
]>

<!--
<default> (1 -> 1)
(phải có 1 phần tử, và chỉ 1 phần tử)

<+> (1 -> vô cùng)
(Phải có ít nhất 1 phần tử,  số lượng phần tử bất kỳ)

<?> (0 -> 1)
(có thể có hoạc không, nhưng chỉ được phép 1 phần tử)

<*> (0 - > vô cùng)
(có thể có hoạc không, số lượng phần tử bất kỳ)
-->

<document>
    <employee>
        <name>
            <lastname>Kelly</lastname>
            <firstname>Grace</firstname>
        </name>
        <hiredate>October 15, 2005</hiredate>
        <projects>
            <project>
                <product>Printer</product>
                <id>111</id>
                <price>$111.00</price>
            </project>
            <project>
                <product>Laptop</product>
                <id>222</id>
                <price>$989.00</price>
            </project>
        </projects>
    </employee>
</document>